
version: '3.7'

services:
    order-api:
        platform: linux/amd64
        image: order-api-image
#        container: order-api-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        
#  mongo:
#    image: mongo
#   restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
